version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/url-db
      SPRING_DATASOURCE_USERNAME: local
      SPRING_DATASOURCE_PASSWORD: local
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: local

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - '5432:5432'
    container_name: db
    environment:
      POSTGRES_DB: url-db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - db:/var/lib/postgres/
volumes:
  db:
    driver: local